{% set name = "azure-mgmt-dns" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: d8379d4bb9194b81b79e5284d875fa6df80707346f2cbb5c5491a20f35266fd0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.dns

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure DNS Managment Client Library for Python.


extra:
  recipe-maintainers:
    - tim-werner
