schema_version: 1

context:
  name: azure-mgmt-dns
  version: 3.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: 6ecdf4e67d8eb5db593ec331e6d9f350616e77c31225c91d266605e03e63b37f

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.dns
      pip_check: false

      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure DNS Managment Client Library for Python.
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
